name: Clean Data and Build Source

on: workflow_dispatch

jobs:
  get-clean-data: 
    runs-on: ubuntu-latest
    env:
      API_KEY: ${{ secrets.NSRDB_SECRET }}

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.9 

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Download NSRDB data (2011 - 2021)
      run: python nsrdb_data_download.py

    - name: Predict NSRDB data for 2022 and 2023
      run: python predict_dhi_2023.py

    - name: Clean the data
      run: python main.py

    - name: Create visualization
      run: python visualize.py

    - name: Check file structure (data)
      run: ls -ltr data/

    - name: Check file structure (html)
      run: ls -ltr html/

    - name: Upload data directory as artifact
      uses: actions/upload-artifact@v2
      with:
        name: Data
        path: data/

    - name: Upload html directory as artifact
      uses: actions/upload-artifact@v2
      with:
        name: HTML
        path: html/
